// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameBook = "book"

// Book 作品表
type Book struct {
	BookID                   int32     `gorm:"column:book_id;primaryKey;autoIncrement:true;comment:作品ID" json:"book_id"`                                                    // 作品ID
	BookNo                   string    `gorm:"column:book_no;not null;comment:短剧编号" json:"book_no"`                                                                         // 短剧编号
	Channel                  int32     `gorm:"column:channel;not null;comment:频道，1=男频，2=女频，0=未设置" json:"channel"`                                                           // 频道，1=男频，2=女频，0=未设置
	IsCompleted              int32     `gorm:"column:is_completed;not null;comment:是否完本，1=完本，0=连载" json:"is_completed"`                                                     // 是否完本，1=完本，0=连载
	Seconds                  int32     `gorm:"column:seconds;not null;comment:时长(秒)" json:"seconds"`                                                                        // 时长(秒)
	Chapters                 int32     `gorm:"column:chapters;not null;comment:章节数" json:"chapters"`                                                                        // 章节数
	Stars                    int32     `gorm:"column:stars;not null;comment:星级派单指数" json:"stars"`                                                                           // 星级派单指数
	Weight                   int32     `gorm:"column:weight;not null;comment:排序用" json:"weight"`                                                                            // 排序用
	IsHidden                 bool      `gorm:"column:is_hidden;not null;comment:日常显示，0=显示，1=隐藏" json:"is_hidden"`                                                           // 日常显示，0=显示，1=隐藏
	IsInBlacklist            bool      `gorm:"column:is_in_blacklist;not null;comment:是否在黑名单，0=否，1=是" json:"is_in_blacklist"`                                               // 是否在黑名单，0=否，1=是
	IsAdUnlock               int32     `gorm:"column:is_ad_unlock;not null;comment:广告解锁 0 关 1 开" json:"is_ad_unlock"`                                                       // 广告解锁 0 关 1 开
	IsSocialMedia            int32     `gorm:"column:is_social_media;not null;comment:社媒可用 0 否 1 是" json:"is_social_media"`                                                 // 社媒可用 0 否 1 是
	SocialMediaReach         int32     `gorm:"column:social_media_reach;not null;comment:社媒使用范围 0 未配置 1 全集 2 免费集 3 30%" json:"social_media_reach"`                          // 社媒使用范围 0 未配置 1 全集 2 免费集 3 30%
	IsMcn                    int32     `gorm:"column:is_mcn;not null;comment:是否MCN使用 0 否 1 是" json:"is_mcn"`                                                                // 是否MCN使用 0 否 1 是
	Status                   string    `gorm:"column:status;not null;default:del;comment:状态，normal=上架，del=下架" json:"status"`                                                // 状态，normal=上架，del=下架
	PublicedAt               time.Time `gorm:"column:publiced_at;not null;default:2000-01-01 00:00:00;comment:公开时间" json:"publiced_at"`                                     // 公开时间
	RefreshedAt              time.Time `gorm:"column:refreshed_at;not null;default:2000-01-01 00:00:00;comment:更新时间" json:"refreshed_at"`                                   // 更新时间
	BookName                 string    `gorm:"column:book_name;not null;comment:书名" json:"book_name"`                                                                       // 书名
	EnglishName              string    `gorm:"column:english_name;not null;comment:英文名" json:"english_name"`                                                                // 英文名
	CoverKey                 string    `gorm:"column:cover_key;not null;comment:封面图key" json:"cover_key"`                                                                   // 封面图key
	HorizontalCoverKey       string    `gorm:"column:horizontal_cover_key;not null;comment:横版封面图key" json:"horizontal_cover_key"`                                           // 横版封面图key
	BannerCoverKey           string    `gorm:"column:banner_cover_key;not null;comment:banner封面图key" json:"banner_cover_key"`                                               // banner封面图key
	ClearBannerCoverKey      string    `gorm:"column:clear_banner_cover_key;not null;comment:清晰banner竖版封面图" json:"clear_banner_cover_key"`                                  // 清晰banner竖版封面图
	HorizontalBannerCoverKey string    `gorm:"column:horizontal_banner_cover_key;not null;comment:横板banner封面图key" json:"horizontal_banner_cover_key"`                       // 横板banner封面图key
	AuthorName               string    `gorm:"column:author_name;not null;comment:作者名" json:"author_name"`                                                                  // 作者名
	AuthorAvatarKey          string    `gorm:"column:author_avatar_key;not null;comment:作者头像key" json:"author_avatar_key"`                                                  // 作者头像key
	Lang                     string    `gorm:"column:lang;not null;default:English;comment:语言" json:"lang"`                                                                 // 语言
	Category                 string    `gorm:"column:category;not null;comment:分类" json:"category"`                                                                         // 分类
	Category2                string    `gorm:"column:category2;not null;comment:二级分类" json:"category2"`                                                                     // 二级分类
	CateID                   int32     `gorm:"column:cate_id;not null;comment:媒体分类ID" json:"cate_id"`                                                                       // 媒体分类ID
	Introduce                string    `gorm:"column:introduce;not null;comment:简介" json:"introduce"`                                                                       // 简介
	Tag                      string    `gorm:"column:tag;not null;comment:标记" json:"tag"`                                                                                   // 标记
	RecommendIntro           string    `gorm:"column:recommend_intro;not null;comment:推荐语" json:"recommend_intro"`                                                          // 推荐语
	Source                   string    `gorm:"column:source;not null;default:DEFAULT;comment:来源" json:"source"`                                                             // 来源
	SourceDetail             string    `gorm:"column:source_detail;not null;comment:详细来源" json:"source_detail"`                                                             // 详细来源
	ProducerID               int32     `gorm:"column:producer_id;not null;comment:制作方ID" json:"producer_id"`                                                                // 制作方ID
	KujiangBookID            int32     `gorm:"column:kujiang_book_id;not null;comment:酷匠作品ID" json:"kujiang_book_id"`                                                       // 酷匠作品ID
	DramaType                int32     `gorm:"column:drama_type;not null;comment:1->成品剧,2->定制剧" json:"drama_type"`                                                          // 1->成品剧,2->定制剧
	BookSource               int32     `gorm:"column:book_source;not null;comment:短剧来源 0 新剧 1 复刻剧，最新：1：自制欧美剧、2：自制翻译剧、3：引入欧美剧、4：引入翻译剧、5：置换欧美剧、6：置换翻译剧"，" json:"book_source"` // 短剧来源 0 新剧 1 复刻剧，最新：1：自制欧美剧、2：自制翻译剧、3：引入欧美剧、4：引入翻译剧、5：置换欧美剧、6：置换翻译剧"，
	OriBookID                int32     `gorm:"column:ori_book_id;not null;comment:原始书号" json:"ori_book_id"`                                                                 // 原始书号
	TotalChargeAmount        float64   `gorm:"column:total_charge_amount;not null;default:0.00;comment:总充值" json:"total_charge_amount"`                                     // 总充值
	TodayChargeAmount        float64   `gorm:"column:today_charge_amount;not null;default:0.00;comment:今日充值" json:"today_charge_amount"`                                    // 今日充值
	YesterdayChargeAmount    float64   `gorm:"column:yesterday_charge_amount;not null;default:0.00;comment:昨日充值" json:"yesterday_charge_amount"`                            // 昨日充值
	ReadCount                int32     `gorm:"column:read_count;not null;comment:总阅读人数" json:"read_count"`                                                                  // 总阅读人数
	TodayReadCount           int32     `gorm:"column:today_read_count;not null;comment:今日阅读人数" json:"today_read_count"`                                                     // 今日阅读人数
	YesterdayReadCount       int32     `gorm:"column:yesterday_read_count;not null;comment:昨日阅读人数" json:"yesterday_read_count"`                                             // 昨日阅读人数
	Remarks                  string    `gorm:"column:remarks;comment:备注" json:"remarks"`                                                                                    // 备注
	CreatedAt                time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`                                         // 创建时间
	UpdatedAt                time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:修改时间" json:"updated_at"`                                         // 修改时间
	IsOriginal               int32     `gorm:"column:is_original;default:2;comment:是否原创(0:非原创,1:原创，2：未编辑【默认】)" json:"is_original"`                                          // 是否原创(0:非原创,1:原创，2：未编辑【默认】)
	IsBindWriter             bool      `gorm:"column:is_bind_writer;comment:是否绑定编剧(0:未绑定【默认】，1：已绑定)" json:"is_bind_writer"`                                                 // 是否绑定编剧(0:未绑定【默认】，1：已绑定)
	WriterID                 int32     `gorm:"column:writer_id;comment:编剧编号" json:"writer_id"`                                                                              // 编剧编号
	CopyrightBy              string    `gorm:"column:copyright_by;not null;comment:版权归属" json:"copyright_by"`                                                               // 版权归属
	ProducerCompany          string    `gorm:"column:producer_company;not null;comment:制作公司" json:"producer_company"`                                                       // 制作公司
	Director                 string    `gorm:"column:director;not null;comment:导演" json:"director"`                                                                         // 导演
	ChannelSource            bool      `gorm:"column:channel_source;not null;comment:渠道来源: 1-自制剧  2-引入剧(中) 3-引入剧(外) 4-其他" json:"channel_source"`                            // 渠道来源: 1-自制剧  2-引入剧(中) 3-引入剧(外) 4-其他
	OwnCopyright             int32     `gorm:"column:own_copyright;comment:有无版权，0: 未知,1:拥有,2:未拥有" json:"own_copyright"`                                                     // 有无版权，0: 未知,1:拥有,2:未拥有
	TagIds                   string    `gorm:"column:tag_ids;comment:标签列表-冗余" json:"tag_ids"`                                                                               // 标签列表-冗余
	BookAttr                 int32     `gorm:"column:book_attr;not null;comment:短剧属性 1 本土剧 2 翻译剧" json:"book_attr"`                                                         // 短剧属性 1 本土剧 2 翻译剧
	DramaRating              bool      `gorm:"column:drama_rating;not null;comment:评级" json:"drama_rating"`                                                                 // 评级
	FirstReleaseTime         time.Time `gorm:"column:first_release_time;not null;default:2000-01-01 00:00:00;comment:首次上线时间" json:"first_release_time"`                     // 首次上线时间
	ReleaseTime              time.Time `gorm:"column:release_time;not null;default:2000-01-01 00:00:00;comment:上线时间" json:"release_time"`                                   // 上线时间
	NativeName               string    `gorm:"column:native_name;not null;comment:本土化剧名" json:"native_name"`                                                                // 本土化剧名
	LanguageName             string    `gorm:"column:language_name;comment:语种名称" json:"language_name"`                                                                      // 语种名称
	LanguageKey              string    `gorm:"column:language_key;comment:语种key" json:"language_key"`                                                                       // 语种key
	MotherBookID             int32     `gorm:"column:mother_book_id;not null;comment:母剧ID" json:"mother_book_id"`                                                           // 母剧ID
	MotherChildType          int32     `gorm:"column:mother_child_type;comment:子母剧类型 0母剧  1子剧" json:"mother_child_type"`                                                    // 子母剧类型 0母剧  1子剧
	DebutTime                time.Time `gorm:"column:debut_time;comment:首发时间" json:"debut_time"`                                                                            // 首发时间
	DramaLength              bool      `gorm:"column:drama_length;not null;default:1;comment:篇幅：1-短篇 2-长篇" json:"drama_length"`                                             // 篇幅：1-短篇 2-长篇
	DecommissionDate         time.Time `gorm:"column:decommission_date;not null;default:2000-01-01 00:00:00;comment:下架时间" json:"decommission_date"`                         // 下架时间
	SourceRootBookID         int32     `gorm:"column:source_root_book_id;not null;comment:母剧子剧的原始短剧id" json:"source_root_book_id"`                                          // 母剧子剧的原始短剧id
	VideoAccount             string    `gorm:"column:video_account;not null;default:sn1;comment:初始sn1 新增ss1,ss2" json:"video_account"`                                      // 初始sn1 新增ss1,ss2
	ListingDate              time.Time `gorm:"column:listing_date;not null;default:2000-01-01 00:00:00;comment:免费渠道可上架日期" json:"listing_date"`                              // 免费渠道可上架日期
	FancyStatus              string    `gorm:"column:fancy_status;not null;default:del;comment:短剧在fancy状态：del-下架 normal-上架" json:"fancy_status"`                            // 短剧在fancy状态：del-下架 normal-上架
}

// TableName Book's table name
func (*Book) TableName() string {
	return TableNameBook
}
