// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user_info_1"

// User 用户信息表
type User struct {
	UserID           int64     `gorm:"column:user_id;primaryKey;comment:用户ID" json:"user_id"`                                  // 用户ID
	Nickname         string    `gorm:"column:nickname;not null;comment:昵称" json:"nickname"`                                    // 昵称
	Avatar           string    `gorm:"column:avatar;not null;comment:用户头像" json:"avatar"`                                      // 用户头像
	Sex              int32     `gorm:"column:sex;not null;comment:性别 0 未知 1 男 2女" json:"sex"`                                  // 性别 0 未知 1 男 2女
	Phone            string    `gorm:"column:phone;not null;comment:手机号" json:"phone"`                                         // 手机号
	Lang             string    `gorm:"column:lang;not null;comment:语种 默认英文" json:"lang"`                                       // 语种 默认英文
	Email            string    `gorm:"column:email;not null;comment:电子邮箱" json:"email"`                                        // 电子邮箱
	Region           string    `gorm:"column:region;not null;comment:国别" json:"region"`                                        // 国别
	Country2         string    `gorm:"column:country2;not null;comment:用户所属国家地区" json:"country2"`                              // 用户所属国家地区
	Country1         string    `gorm:"column:country1;not null;default:OTHER;comment:用户所属国家地区" json:"country1"`                // 用户所属国家地区
	Country          string    `gorm:"column:country;not null;comment:用户所属国家地区" json:"country"`                                // 用户所属国家地区
	LimitCountry     string    `gorm:"column:limit_country;comment:限定使用(支付)国家" json:"limit_country"`                           // 限定使用(支付)国家
	IsPayUser        int32     `gorm:"column:is_pay_user;not null;comment:是否付费用户（0不是 1是）" json:"is_pay_user"`                  // 是否付费用户（0不是 1是）
	UserType         int32     `gorm:"column:user_type;not null;default:1;comment:用户类型：1 流失用户；2 犹豫用户；3 付费用户" json:"user_type"` // 用户类型：1 流失用户；2 犹豫用户；3 付费用户
	IP               string    `gorm:"column:ip;not null;comment:用户注册ip" json:"ip"`                                            // 用户注册ip
	JoinAt           time.Time `gorm:"column:join_at;not null;default:2000-01-01 00:00:00;comment:注册时间" json:"join_at"`        // 注册时间
	Status           int32     `gorm:"column:status;not null;default:1;comment:状态（0封禁1正常2注销）" json:"status"`                   // 状态（0封禁1正常2注销）
	SpreadID         int32     `gorm:"column:spread_id;not null;comment:推广ID" json:"spread_id"`                                // 推广ID
	CreatedAt        time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_at"`    // 创建时间
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;default:CURRENT_TIMESTAMP;comment:修改时间" json:"updated_at"`    // 修改时间
	PromotionChannel int32     `gorm:"column:promotion_channel;comment:推广渠道,见枚举类定义" json:"promotion_channel"`                  // 推广渠道,见枚举类定义
	Platform         int32     `gorm:"column:platform;comment:注册时的平台" json:"platform"`                                         // 注册时的平台
	Version          string    `gorm:"column:version;not null;comment:客户端版本号" json:"version"`                                  // 客户端版本号
	Ct               string    `gorm:"column:ct;comment:城市city" json:"ct"`                                                     // 城市city
	St               string    `gorm:"column:st;comment:洲state" json:"st"`                                                     // 洲state
	Zp               string    `gorm:"column:zp;comment:postal_code" json:"zp"`                                                // postal_code
	RandNum          int32     `gorm:"column:rand_num;not null;comment:随机数" json:"rand_num"`                                   // 随机数
	Gaid             string    `gorm:"column:gaid;not null;comment:gaid" json:"gaid"`                                          // gaid
	AppsflyerID      string    `gorm:"column:appsflyer_id;not null;comment:af的appsflyer_id" json:"appsflyer_id"`               // af的appsflyer_id
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
