app:
  name: drama-go
  port: 8081
  env: dev

database:
  dsn: test:*@tcp(*:3306)/kj_hw_drama_main?charset=utf8mb4&parseTime=True&loc=Local

redis:
  addr: *
  password: "*"
  db: 4
  pool_size: 10
  min_idle_conns: 5

jwt:
  secret_key: "drama-go-jwt-secret-key-2024"
  expire: 24h
